mySite/githubAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'githubAPI'

urlpatterns = [
    path('', views.github,name='github')
]

mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('github/', include('githubAPI.urls')),
]

mySite/polls/urls.py
from django.urls import path
from . import views # import the views file

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote')
]

mySite/githubAPI/models.py
from django.db import models

# Create your models here.

mySite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publication_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publication_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mySite/githubAPI/views.py
from django.shortcuts import render
import requests # for getting the API response
# # Create your views here.
from django.http import HttpResponse
from django.shortcuts import render

def github(request):
    if request.method == 'POST':
        return HttpResponse(request.POST['username'])
    return render(request, 'githubAPI/base.html')

mySite/mySite/views.py
from django.shortcuts import render

def home(requests):
    return render(requests, 'index.html')

mySite/polls/views.py
from .models import Question, Choice # database API
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions(not including those set to be published in the future)."""
        return Question.objects.filter(
        publication_date__lte = timezone.now()
        ).order_by('-publication_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mySite/githubAPI/templates/githubAPI/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Github Api</title>
  </head>
<body style="align-content: center">
    <form action="." method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username"> Enter Github Username: </label>
            <input placeholder="Username " type="text" class="form-control" name="username">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
</body>
</html>

mySite/mySite/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Django Project</title>
  </head>
<body>
    <h2> Django Web Apps </h2>
    <hr>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar" href="{% url 'polls:index' %}">/Polls App</a>
        <a class="navbar" href="{% url 'githubAPI:github' %}"> /Github Api</a>
    </nav>
    
    <footer class="page-footer font-small blue">DHIRAJ SAHARIA
        <div class="footer-copyright text-center py-3">Made with ❤️
        </div>
    </footer>
</body>
</html>

mySite/polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong> {{error_message}}</strong> </p> {%endif%}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {%csrf_token%}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}"> {{choice.choice_text}}</label>
        <br>
    {%endfor%}
    <input type="submit" value="Vote">
</form>

mySite/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<h1>-- Django Polls App --</h1>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}"> {{question.question_text}}</a>
        </li>
        {% endfor%}
    </ul>
    {%else%}
        <p> No Polls are avalable. </p>
{%endif%}
<footer> Dhiraj Saharia</footer>

mySite/polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>